### ISSUE TITLE
Category bubbles are not always placed correctly

### ISSUE THREAD

**Issue by cassiebaer** [EtherList/EtherList#23]
Screenshot below. One of the categories is placed too high and is being cut off

![Screenshot](https://dl.dropboxusercontent.com/s/n1w4yjggn68uowv/Screenshot%202016-08-14%2017.07.56.png)

**Comment by natgrigorovskaya** [comment]
Thanks!! Will fix

**Comment by natgrigorovskaya** [comment]
fixed
