### ISSUE TITLE
Database architecture

### ISSUE THREAD

**Issue by 08martinm** [EtherList/EtherList#33]
Redesign database to store current listings in one database and past listings in another. Maybe include worker to transfer information from one to the other.

**Comment by donovanCarreno** [comment]
I just added this to the Listing table:

status: {
    type: Sequelize.STRING,
    allowNull: false,
    defaultValue: 'OPEN'
  }

I imagine that we'll then have some sort of function that will update the value to 'COMPLETE' once the transaction is done.

Thoughts?

**Comment by cassiebaer** [comment]
Let's us a Sequelize.BOOLEAN instead. It'll be much more space efficient

**Comment by cassiebaer** [comment]
closed by #36
